# -*- coding: utf-8 -*-
"""
🧠 Nemotron-3-Nano-4B SFT with Unsloth on Modal

Based on the LFM2.5 Unsloth/Modal pipeline, adapted for NVIDIA Nemotron-3-Nano-4B.
Nemotron 3 is a hybrid Mamba-Transformer MoE model with native <think> reasoning
support.  This script expects a JSONL dataset with OpenAI-style "messages" arrays
(e.g. generated by data/distill_dataset_po/create_training_dataset_nemotron.py).

To run:
1. modal run sft/nemotron_nano_sft_with_unsloth.py --action upload_data
2. Upload your training data to Modal volume:
   modal volume put nemotron-nano-finetune-volume ./nemotron_training_data.jsonl /data/nemotron_training_data.jsonl
3. Train:
   modal run sft/nemotron_nano_sft_with_unsloth.py --action train
4. Train + Auto-Deploy:
   modal run sft/nemotron_nano_sft_with_unsloth.py --action train --repo-name yourusername/model-name
"""

import json
import os
from pathlib import Path

import modal

# Configuration
VOL_MOUNT_PATH = Path("/vol")
BASE_MODEL = "unsloth/NVIDIA-Nemotron-3-Nano-4B"

# HuggingFace token. Read from the environment so the literal value
# never has to live in source. Override at runtime via --hf-token.
HF_TOKEN = os.environ.get("HF_TOKEN", "")

# Training configuration
MAX_SEQ_LENGTH = 2048
R = 16
LORA_ALPHA = 16
BATCH_SIZE = 2
GRADIENT_ACCUMULATION_STEPS = 4
MAX_STEPS = 120
LEARNING_RATE = 2e-4
NUM_EPOCHS = 1

# Create Modal image with all dependencies
# Use Unsloth's official Docker image as the base so mamba-ssm, causal-conv1d,
# CUDA toolkit (nvcc), and unsloth itself are already preinstalled.
image = (
    modal.Image.from_registry(
        "unsloth/unsloth:latest",
        setup_dockerfile_commands=["ENTRYPOINT []", "CMD []"],
    )
    .apt_install(
        "curl", "libcurl4-openssl-dev", "libssl-dev", "git", "cmake", "build-essential",
    )
    .run_commands(
        "pip install --upgrade --force-reinstall --no-cache-dir --no-deps unsloth unsloth_zoo",
    )
)

app = modal.App(name="nemotron-nano-finetune", image=image)

# Create persistent volume for data and models
output_vol = modal.Volume.from_name("nemotron-nano-finetune-volume", create_if_missing=True)


@app.function(
    gpu="A10G",
    timeout=7200,  # 2 hours
    volumes={VOL_MOUNT_PATH: output_vol},
)
def finetune(
    model_id: str = BASE_MODEL,
    max_seq_length: int = MAX_SEQ_LENGTH,
    batch_size: int = BATCH_SIZE,
    gradient_accumulation_steps: int = GRADIENT_ACCUMULATION_STEPS,
    max_steps: int = MAX_STEPS,
    learning_rate: float = LEARNING_RATE,
    num_train_epochs: int = NUM_EPOCHS,
    output_model_name: str = None,
    repo_name: str = None,
    hf_token: str = None,
    quantization_method: str = "f16",
):
    """
    Finetune Nemotron-3-Nano-4B on the provided dataset using Unsloth.
    """
    from unsloth import FastLanguageModel
    import torch
    from datasets import load_dataset
    from trl import SFTTrainer, SFTConfig
    from unsloth.chat_templates import standardize_data_formats, train_on_responses_only

    if output_model_name is None:
        model_name = model_id.split("/")[-1]
        output_model_name = f"finetuned_{model_name}"

    print(f"Starting finetuning of {model_id}")
    print(f"Configuration: batch_size={batch_size}, max_steps={max_steps}, lr={learning_rate}")

    # Load model with Unsloth
    print("Loading model with Unsloth...")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=model_id,
        max_seq_length=max_seq_length,
        load_in_4bit=False,
        load_in_8bit=False,
        load_in_16bit=True,
        full_finetuning=False,
        trust_remote_code=True,
    )

    # Add LoRA adapters
    print("Adding LoRA adapters...")
    model = FastLanguageModel.get_peft_model(
        model,
        r=R,
        target_modules=[
            "q_proj", "k_proj", "v_proj", "o_proj",
            "gate_proj", "up_proj", "down_proj",
            "in_proj", "out_proj",
        ],
        lora_alpha=LORA_ALPHA,
        lora_dropout=0,
        bias="none",
        use_gradient_checkpointing="unsloth",
        random_state=3407,
        use_rslora=False,
        loftq_config=None,
    )

    # Check if data files exist
    data_path = VOL_MOUNT_PATH / "data" / "nemotron_training_data.jsonl"
    if not data_path.exists():
        raise FileNotFoundError(f"Data file not found at {data_path}. Please upload first.")

    # Load dataset
    print("Loading dataset...")
    dataset = load_dataset("json", data_files=str(data_path), split="train")

    # Standardize dataset format
    dataset = standardize_data_formats(dataset)

    # Apply chat template
    def formatting_prompts_func(examples):
        texts = tokenizer.apply_chat_template(
            examples["messages"],
            tokenize=False,
            add_generation_prompt=False,
        )
        return {"text": [x.removeprefix(tokenizer.bos_token) for x in texts]}

    dataset = dataset.map(formatting_prompts_func, batched=True)

    # Setup training arguments
    training_args = SFTConfig(
        dataset_text_field="text",
        per_device_train_batch_size=batch_size,
        gradient_accumulation_steps=gradient_accumulation_steps,
        warmup_steps=5,
        max_steps=max_steps if max_steps else None,
        num_train_epochs=num_train_epochs if not max_steps else 1,
        learning_rate=learning_rate,
        logging_steps=1,
        optim="adamw_8bit",
        weight_decay=0.01,
        lr_scheduler_type="linear",
        seed=3407,
        report_to="none",
    )

    # Create trainer
    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=dataset,
        eval_dataset=None,
        args=training_args,
    )

    # Train only on assistant responses
    # Unsloth's Nemotron examples use the same im_start markers as other models
    trainer = train_on_responses_only(
        trainer,
        instruction_part="<|im_start|>user\n",
        response_part="<|im_start|>assistant\n",
    )

    # Show memory stats
    gpu_stats = torch.cuda.get_device_properties(0)
    start_gpu_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
    max_memory = round(gpu_stats.total_memory / 1024 / 1024 / 1024, 3)
    print(f"GPU = {gpu_stats.name}. Max memory = {max_memory} GB.")
    print(f"{start_gpu_memory} GB of memory reserved.")

    # Train
    print("Starting training...")
    trainer_stats = trainer.train()

    # Show final stats
    used_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
    used_memory_for_lora = round(used_memory - start_gpu_memory, 3)
    used_percentage = round(used_memory / max_memory * 100, 3)
    lora_percentage = round(used_memory_for_lora / max_memory * 100, 3)
    print(f"{trainer_stats.metrics['train_runtime']} seconds used for training.")
    print(f"{round(trainer_stats.metrics['train_runtime']/60, 2)} minutes used for training.")
    print(f"Peak reserved memory = {used_memory} GB.")
    print(f"Peak reserved memory for training = {used_memory_for_lora} GB.")
    print(f"Peak reserved memory % of max memory = {used_percentage} %.")
    print(f"Peak reserved memory for training % of max memory = {lora_percentage} %.")

    # Save model locally to volume
    output_path = VOL_MOUNT_PATH / "models" / output_model_name
    output_path.mkdir(parents=True, exist_ok=True)

    print(f"Saving model to {output_path}...")
    model.save_pretrained(str(output_path))
    tokenizer.save_pretrained(str(output_path))

    # Commit volume
    output_vol.commit()

    print("✅ Finetuning completed successfully!")
    print(f"Model saved to: {output_path}")

    # Push to HuggingFace Hub as merged weights + GGUF if repo_name is provided
    # The merged weights are required for SGLang/vLLM serving;
    # GGUF is kept for llama.cpp / local use.
    if repo_name and hf_token:
        from huggingface_hub import login

        login(token=hf_token)

        print(f"\nPushing merged 16-bit model to https://huggingface.co/{repo_name}")
        model.push_to_hub_merged(
            repo_name,
            tokenizer,
            save_method="merged_16bit",
            token=hf_token,
        )
        print(f"✅ Merged model pushed to https://huggingface.co/{repo_name}")

        print(f"\nPushing GGUF to https://huggingface.co/{repo_name}")
        print(f"Quantization: {quantization_method}")
        model.push_to_hub_gguf(
            repo_name,
            tokenizer,
            quantization_method=quantization_method,
            token=hf_token,
        )
        print(f"✅ GGUF pushed to https://huggingface.co/{repo_name}")
    else:
        print(f"\nTo download locally:")
        print(f"  modal volume get nemotron-nano-finetune-volume /models/{output_model_name} ./{output_model_name}")

    return str(output_path)


@app.function(volumes={VOL_MOUNT_PATH: output_vol})
def upload_data():
    """
    Setup data directory in Modal volume.
    Run this first, then upload your nemotron_training_data.jsonl file.
    """
    data_dir = VOL_MOUNT_PATH / "data"
    data_dir.mkdir(parents=True, exist_ok=True)

    print(f"Data directory created at: {data_dir}")
    print("Upload your training data:")
    print(f"  modal volume put nemotron-nano-finetune-volume ./nemotron_training_data.jsonl /data/nemotron_training_data.jsonl")

    output_vol.commit()


@app.function(volumes={VOL_MOUNT_PATH: output_vol}, gpu="T4")
def push_to_hub(
    hf_token: str,
    model_name: str,
    repo_name: str,
    quantization_method: str | list[str] = "f16",
):
    """
    Fallback: Push a previously saved model to HuggingFace Hub as GGUF.
    """
    from huggingface_hub import login
    from unsloth import FastLanguageModel

    model_path = VOL_MOUNT_PATH / "models" / model_name
    if not model_path.exists():
        raise FileNotFoundError(f"Model not found at {model_path}")

    print(f"Loading model from {model_path}")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=str(model_path),
        max_seq_length=MAX_SEQ_LENGTH,
        load_in_4bit=False,
        load_in_8bit=False,
        load_in_16bit=True,
        trust_remote_code=True,
    )

    print(f"Logging in to HuggingFace Hub...")
    login(token=hf_token)

    print(f"Pushing model to https://huggingface.co/{repo_name}")
    print(f"Quantization: {quantization_method}")

    model.push_to_hub_gguf(
        repo_name,
        tokenizer,
        quantization_method=quantization_method,
        token=hf_token,
    )

    print(f"✅ Model successfully pushed to https://huggingface.co/{repo_name}")


@app.local_entrypoint()
def main(
    action: str = "train",
    model_id: str = BASE_MODEL,
    batch_size: int = BATCH_SIZE,
    max_steps: int = MAX_STEPS,
    epochs: int = NUM_EPOCHS,
    output_model_name: str = None,
    repo_name: str = None,
    quantization: str = "f16",
    hf_token: str = None,
):
    """
    Local entrypoint for running the Nemotron fine-tuning pipeline.
    """
    if action == "upload_data":
        print("Setting up data directory...")
        upload_data.remote()
        print("\nNext, upload your data file:")
        print("  modal volume put nemotron-nano-finetune-volume ./nemotron_training_data.jsonl /data/nemotron_training_data.jsonl")

    elif action == "train":
        print(f"Starting finetuning on Modal with GPU...")
        effective_max_steps = max_steps if max_steps > 0 else None
        effective_epochs = epochs if not effective_max_steps else 1

        if output_model_name is None:
            model_name_base = model_id.split("/")[-1]
            effective_model_name = f"finetuned_{model_name_base}"
        else:
            effective_model_name = output_model_name

        effective_hf_token = hf_token or HF_TOKEN

        # Parse quantization methods
        if "," in quantization:
            quant_methods = [q.strip() for q in quantization.split(",")]
        else:
            quant_methods = quantization

        result = finetune.remote(
            model_id=model_id,
            batch_size=batch_size,
            max_steps=effective_max_steps,
            num_train_epochs=effective_epochs,
            output_model_name=effective_model_name,
            repo_name=repo_name,
            hf_token=effective_hf_token if repo_name else None,
            quantization_method=quant_methods,
        )
        print(f"\n✅ Training complete! Model saved at: {result}")

        if repo_name:
            print(f"✅ Model also pushed to: https://huggingface.co/{repo_name}")
        else:
            print(f"\nTo auto-deploy after training, add: --repo-name yourusername/model-name")

    else:
        print(f"Unknown action: {action}")
        print("Valid actions: upload_data, train")


if __name__ == "__main__":
    import sys

    action = sys.argv[1] if len(sys.argv) > 1 else "train"
    main(action=action)
